### ISSUE TITLE
CSS - opacity property affects positioning - Chrome 57 (MacOS Sierra)

### ISSUE THREAD

**Issue by camelCaseD** [toddjordan/ember-cli-tutorial-style#4]
Just started going through the Guide and noticed after I installed this addon that there is a bug in how the logo is rendered in the menu. For some reason that I can't think of at the moment the `opacity` property seems to be affecting positioning of the text, see below.
![opacity-bug](https://cloud.githubusercontent.com/assets/1644022/24029835/46b3b292-0a96-11e7-82e1-a9f5d257fabc.gif)

I only tested this in Chrome and Safari which the latter did not affect positioning.

**Comment by toddjordan** [comment]
Hi @camelCaseD thank you for reporting.  I'll take a look at it, but it probably won't be until after emberconf (2 weeks).  If you come up with a solution, I'd be happy to help you get a PR through.

**Comment by camelCaseD** [comment]
Ignore the PR created on my fork (made a mistake in the Github UI). In order for the styles I modified to work correctly, the guide will have to be updated as it was the floats from the `.left` that was causing the glitch. See #5 for more info on what parts in the guide needs to be updated.

**Comment by toddjordan** [comment]
Fixed! thanks @camelCaseD ❤️
