### ISSUE TITLE
Tomster not found

### ISSUE THREAD

**Issue by batisteo** [toddjordan/ember-cli-tutorial-style#6]
The CSS links to http://emberjs.com/images/tomsters/teaching.png which is not found.

**Comment by toddjordan** [comment]
Ah, yes.  I seem to remember them changing the links recently.  Good catch and thanks for reporting!  I'll get to this in the next couple days (unless you can beat me to it with a pr ;-)

**Comment by acorncom** [comment]
This was broken when we merged https://github.com/emberjs/website/pull/2840 (hadn't realized we had things in this add-on that relied on a static image). I think it'd probably make the most sense to have that image locally in this add-on ...

**Comment by toddjordan** [comment]
Followed advice of @acorncom and move the image locally.  Fixed in version 1.0.1 of the addon.  To apply the changes, get this version of the addon and re-run the addon's blueprint: `ember g ember-cli-tutorial-style`
